- include_vars: "vars/{{ ansible_facts['os_family'] }}.yaml"

- name: Instalar el paquete de apache y https
  package:
    name: "{{ package_name }}"
    state: present
  when: >
      ( 
        ansible_distribution in ['RedHat', 'Fedora'] and
        ansible_distribution_major_version == "8" )
        or
      (
        ansible_distribution in ['Debian'] and
        ansible_distribution_major_version == '11'
      )

- name: Iniciar el servicio
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  loop: "{{ service_name }}"

- set_fact:
    test: True
